### ISSUE TITLE
Add appropriate comments to tha code 

### ISSUE THREAD

**Issue by LalitDhane** [LalitDhane/blog#3] opened 2022-08-12 16:41 UTC

**Comment by hassana123** [comment] 2022-08-13 17:57
Would like to work on this @LalitDhane

**Comment by LalitDhane** [comment] 2022-08-14 09:39
Good to see you are interested in contributing!

I've assigned you for this issue

**Comment by Jangyaseni666** [comment] 2022-12-19 18:27
I would like to help add appropriate comments(assuming the issue is not fixed as it is still open). Can you please assign this to me?

**Comment by LalitDhane** [comment] 2022-12-20 03:14
Sure

**Comment by Jangyaseni666** [comment] 2022-12-20 04:18
> Sure
> 

Thanku!

**Closed as completed** 2022-12-25 10:01 UTC
Labels: documentation, good first issue, newbie
